use tree_sitter::{Parser, Query, QueryCursor};

pub struct Transpiler {
    parser: Parser,
    query: Query,
}

impl Transpiler {
    pub fn new() -> Self {
        let mut parser = Parser::new();
        let language = tree_sitter_ruby::language();
        parser.set_language(language).expect("Error loading Ruby grammar");

        // Look for the rbs-inline comment pattern + the method name
        let query = Query::new(
            language,
            r#"
            (comment) @anno
            .
            (method (identifier) @name)
            "#,
        ).expect("Error compiling Query");

        Self { parser, query }
    }

    pub fn process_source(&mut self, source: &str) -> String {
        let tree = self.parser.parse(source, None).unwrap();
        let mut cursor = QueryCursor::new();
        let mut output = String::from("# @generated by Sentinel\n\n");

        let matches = cursor.matches(&self.query, tree.root_node(), source.as_bytes());

        for m in matches {
            let anno_node = m.captures[0].node;
            let name_node = m.captures[1].node;

            let anno_text = &source[anno_node.start_byte()..anno_node.end_byte()];
            let name_text = &source[name_node.start_byte()..name_node.end_byte()];

            // Transform "#: (String) -> void" -> "def name: (String) -> void"
            if let Some(sig) = anno_text.strip_prefix("#: ") {
                output.push_str(&format!("def {}: {}\n", name_text, sig));
            }
        }
        output
    }
}
