use tree_sitter::{Parser, Query, QueryCursor};
use std::fs;
use std::path::Path;

pub struct SentinelTranspiler {
    parser: Parser,
    query: Query,
}

impl SentinelTranspiler {
    pub fn new() -> Self {
        let mut parser = Parser::new();
        let lang = tree_sitter_ruby::language();
        parser.set_language(lang).expect("Error loading Ruby grammar");
        
        // Query to find rbs-inline comments (e.g., #: (String) -> void) 
        // and the method definition immediately following it.
        let query = Query::new(lang, r#"
            (comment) @type_annotation
            .
            (method (identifier) @method_name)
        "#).expect("Error compiling Tree-sitter query");

        Self { parser, query }
    }

    pub fn transpile_file(&mut self, rb_path: &Path) -> Result<String, Box<dyn std::error::Error>> {
        let source = fs::read_to_string(rb_path)?;
        let tree = self.parser.parse(&source, None).ok_or("Failed to parse")?;
        let mut cursor = QueryCursor::new();

        let mut rbs_output = String::new();
        rbs_output.push_str("# Generated by Sentinel - Do not edit manually\n\n");

        for m in cursor.matches(&self.query, tree.root_node(), source.as_bytes()) {
            let annotation = &source[m.captures[0].node.start_byte()..m.captures[0].node.end_byte()];
            let method_name = &source[m.captures[1].node.start_byte()..m.captures[1].node.end_byte()];
            
            // Convert "#: (String) -> void" to "def method_name: (String) -> void"
            if let Some(sig) = annotation.strip_prefix("#: ") {
                rbs_output.push_str(&format!("def {}: {}\n", method_name, sig.trim()));
            }
        }
        Ok(rbs_output)
    }
}
