use std::fs;
use std::path::Path;
use tree_sitter::{Parser, Query, QueryCursor};

pub struct SentinelTranspiler {
    parser: Parser,
    query: Query,
}

impl SentinelTranspiler {
    pub fn new() -> Self {
        let mut parser = Parser::new();
        let lang = tree_sitter_ruby::language();
        parser
            .set_language(lang)
            .expect("Error loading Ruby grammar");

        // Updated query: Removed problematic leading whitespace and simplified the anchor
        let query_code = r#"
(class name: (constant) @class_name)

(
  (comment) @type_annotation
  .
  (method name: (identifier) @method_name)
  (#match? @type_annotation "^#:")
)
"#;

        let query = Query::new(lang, query_code).expect("Error compiling Tree-sitter query");

        Self { parser, query }
    }

    pub fn transpile_file(&mut self, rb_path: &Path) -> Result<String, Box<dyn std::error::Error>> {
        let source = fs::read_to_string(rb_path)?;
        let tree = self.parser.parse(&source, None).ok_or("Failed to parse")?;
        let mut cursor = QueryCursor::new();

        let mut rbs_output = String::new();
        rbs_output.push_str("# Generated by Sentinel - Do not edit manually\n\n");

        let mut current_class = "UnknownClass".to_string();
        let mut methods_rbs = String::new();

        // Single pass to gather class name AND method signatures
        for m in cursor.matches(&self.query, tree.root_node(), source.as_bytes()) {
            let mut annotation = "";
            let mut method_name = "";

            for capture in m.captures {
                let capture_name = &self.query.capture_names()[capture.index as usize];

                // Fix E0308: Use .as_str() to match against literals
                match capture_name.as_str() {
                    "class_name" => {
                        current_class =
                            source[capture.node.start_byte()..capture.node.end_byte()].to_string();
                    }
                    "type_annotation" => {
                        annotation = &source[capture.node.start_byte()..capture.node.end_byte()];
                    }
                    "method_name" => {
                        method_name = &source[capture.node.start_byte()..capture.node.end_byte()];
                    }
                    _ => {}
                }
            }

            // Only append to methods if we have a valid pair
            if !annotation.is_empty() && !method_name.is_empty() {
                if let Some(sig) = annotation.strip_prefix("#: ") {
                    methods_rbs.push_str(&format!("  def {}: {}\n", method_name, sig.trim()));
                }
            }
        }

        rbs_output.push_str(&format!("class {}\n", current_class));
        rbs_output.push_str(&methods_rbs);
        rbs_output.push_str("end\n");

        Ok(rbs_output)
    }
}
